version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: dockerfilegunicorn
    volumes:
    - "/home/ubuntu/wrkdir/spert/spert/data:/data:rw"
    ports:
      - "8082:8082"
    networks:
      - default
      - kgprecommenderbackend_default
networks:
  kgprecommenderbackend_default:
    external: true